version: "3.8"
   
services:
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            # - /usr/local/var/postgres/data:/var/lib/postgresql/data  #macos
            # - /var/lib/postgres/data:/var/lib/postgresql/data  #linux
            - ./data:/var/lib/postgresql/data  #windows
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        restart: always
    web:
        build: .
        container_name: web
        restart: always
        volumes:
            - .:/usr/src/app
        command: python run.py
        ports:
            - "8000:8000"
        depends_on:
            - pgdb