version: "3.8"
   
services:
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
            - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        restart: always
    web:
        build: .
        container_name: web
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
        command: python run.py
        restart: always
        depends_on:
            - pgdb